version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: ./Dockerfiles/react.Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./:/src
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    depends_on:
      - "django_app"
    stdin_open: true
    tty: true
  django_app:
    build:
      context: .
      dockerfile: ./Dockerfiles/django.Dockerfile
    env_file:
      - ./.env
    container_name: django_app
    environment:
      SELENIUM_URL: "http://selenium:4444/wd/hub"
    ports:
      - "8000:8000"
    volumes:
      - ./django_api:/django_api
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             trap 'python3 -u manage.py runserver 0.0.0.0:8000' EXIT &&
             export DJANGO_SUPERUSER_USERNAME=${SUPER_USER_NAME} &&
             export DJANGO_SUPERUSER_EMAIL=${SUPER_USER_EMAIL} &&
             export DJANGO_SUPERUSER_PASSWORD=${SUPER_USER_PASS} &&
             python3 manage.py createsuperuser --no-input &&
             daphne -b 0.0.0.0 -p 8000 dlion_project.asgi:application"
    depends_on:
      - "redis"
    tty: true
  selenium:
    image: seleniarm/standalone-chromium
    container_name: selenium
    environment:
      - SE_NODE_MAX_SESSIONS=3
    ports:
      - 4444:4444
      - 15900:5900
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - "django_app"
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
