version: "3"

services:
  react-app:
    build:
      context: .
      dockerfile: ./Dockerfiles/react.Dockerfile
    volumes:
      - ./:/src
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    depends_on:
      - "django_app"
    stdin_open: true
    tty: true
  django_app:
    build:
      context: .
      dockerfile: ./Dockerfiles/django.Dockerfile
    container_name: django_app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    ports:
      - "8000:8000"
    volumes:
      - ./django_api:/django_api
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 -u manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    tty: true
  selenium:
    image: seleniarm/standalone-chromium
    environment:
      - SE_NODE_MAX_SESSIONS=3
    ports:
      - 4444:4444
      - 15900:5900
    volumes:
      - /dev/shm:/dev/shm
