# Generated by Django 3.2 on 2022-07-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='categories',
            field=models.TextField(default='[]'),
        ),
    ]
