# Generated by Django 3.2 on 2022-06-30 18:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedata',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='filedata',
            name='categories',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='filedata',
            name='cover_image',
            field=models.FileField(null=True, upload_to=core.models.saveCoverDataPath),
        ),
        migrations.AddField(
            model_name='filedata',
            name='main_data_size',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='filedata',
            name='main_data_status',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='filedata',
            name='short_video_path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='filedata',
            name='video_data',
            field=models.FileField(null=True, upload_to=core.models.saveMainDataPath),
        ),
        migrations.AddField(
            model_name='filedata',
            name='video_data_status',
            field=models.TextField(default='{"hm3u8": 0, "lowmp4": 0, "lm3u8": 0, "playlist": 0, "allcomplete": 0, "completetotal": 0}'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
