# Generated by Django 3.2 on 2022-07-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_filedata_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedata',
            old_name='main_data_status',
            new_name='main_data_type',
        ),
    ]
